/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Courses service. Represents a row in the &quot;mz_Courses&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.CoursesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.CoursesImpl}.
 * </p>
 *
 * @author mzos
 * @see Courses
 * @see com.test.model.impl.CoursesImpl
 * @see com.test.model.impl.CoursesModelImpl
 * @generated
 */
public interface CoursesModel extends BaseModel<Courses> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a courses model instance should use the {@link Courses} interface instead.
	 */

	/**
	 * Returns the primary key of this courses.
	 *
	 * @return the primary key of this courses
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this courses.
	 *
	 * @param primaryKey the primary key of this courses
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the c ID of this courses.
	 *
	 * @return the c ID of this courses
	 */
	public long getCId();

	/**
	 * Sets the c ID of this courses.
	 *
	 * @param cId the c ID of this courses
	 */
	public void setCId(long cId);

	/**
	 * Returns the c name of this courses.
	 *
	 * @return the c name of this courses
	 */
	@AutoEscape
	public String getCName();

	/**
	 * Sets the c name of this courses.
	 *
	 * @param cName the c name of this courses
	 */
	public void setCName(String cName);

	/**
	 * Returns the c cat of this courses.
	 *
	 * @return the c cat of this courses
	 */
	@AutoEscape
	public String getCCat();

	/**
	 * Sets the c cat of this courses.
	 *
	 * @param cCat the c cat of this courses
	 */
	public void setCCat(String cCat);

	/**
	 * Returns the c desc of this courses.
	 *
	 * @return the c desc of this courses
	 */
	@AutoEscape
	public String getCDesc();

	/**
	 * Sets the c desc of this courses.
	 *
	 * @param cDesc the c desc of this courses
	 */
	public void setCDesc(String cDesc);

	/**
	 * Returns the c preq of this courses.
	 *
	 * @return the c preq of this courses
	 */
	@AutoEscape
	public String getCPreq();

	/**
	 * Sets the c preq of this courses.
	 *
	 * @param cPreq the c preq of this courses
	 */
	public void setCPreq(String cPreq);

	/**
	 * Returns the c duration of this courses.
	 *
	 * @return the c duration of this courses
	 */
	public int getCDuration();

	/**
	 * Sets the c duration of this courses.
	 *
	 * @param cDuration the c duration of this courses
	 */
	public void setCDuration(int cDuration);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Courses courses);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Courses> toCacheModel();

	@Override
	public Courses toEscapedModel();

	@Override
	public Courses toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}