/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EnrollCourse service. Represents a row in the &quot;mz_EnrollCourse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.EnrollCourseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.EnrollCourseImpl}.
 * </p>
 *
 * @author mzos
 * @see EnrollCourse
 * @see com.test.model.impl.EnrollCourseImpl
 * @see com.test.model.impl.EnrollCourseModelImpl
 * @generated
 */
public interface EnrollCourseModel extends BaseModel<EnrollCourse> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a enroll course model instance should use the {@link EnrollCourse} interface instead.
	 */

	/**
	 * Returns the primary key of this enroll course.
	 *
	 * @return the primary key of this enroll course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this enroll course.
	 *
	 * @param primaryKey the primary key of this enroll course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the e ID of this enroll course.
	 *
	 * @return the e ID of this enroll course
	 */
	public long getEId();

	/**
	 * Sets the e ID of this enroll course.
	 *
	 * @param eId the e ID of this enroll course
	 */
	public void setEId(long eId);

	/**
	 * Returns the ef name of this enroll course.
	 *
	 * @return the ef name of this enroll course
	 */
	@AutoEscape
	public String getEfName();

	/**
	 * Sets the ef name of this enroll course.
	 *
	 * @param efName the ef name of this enroll course
	 */
	public void setEfName(String efName);

	/**
	 * Returns the egen of this enroll course.
	 *
	 * @return the egen of this enroll course
	 */
	@AutoEscape
	public String getEgen();

	/**
	 * Sets the egen of this enroll course.
	 *
	 * @param egen the egen of this enroll course
	 */
	public void setEgen(String egen);

	/**
	 * Returns the email of this enroll course.
	 *
	 * @return the email of this enroll course
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this enroll course.
	 *
	 * @param email the email of this enroll course
	 */
	public void setEmail(String email);

	/**
	 * Returns the econt of this enroll course.
	 *
	 * @return the econt of this enroll course
	 */
	public long getEcont();

	/**
	 * Sets the econt of this enroll course.
	 *
	 * @param econt the econt of this enroll course
	 */
	public void setEcont(long econt);

	/**
	 * Returns the equal of this enroll course.
	 *
	 * @return the equal of this enroll course
	 */
	@AutoEscape
	public String getEqual();

	/**
	 * Sets the equal of this enroll course.
	 *
	 * @param equal the equal of this enroll course
	 */
	public void setEqual(String equal);

	/**
	 * Returns the ecourse of this enroll course.
	 *
	 * @return the ecourse of this enroll course
	 */
	@AutoEscape
	public String getEcourse();

	/**
	 * Sets the ecourse of this enroll course.
	 *
	 * @param ecourse the ecourse of this enroll course
	 */
	public void setEcourse(String ecourse);

	/**
	 * Returns the ebatch of this enroll course.
	 *
	 * @return the ebatch of this enroll course
	 */
	@AutoEscape
	public String getEbatch();

	/**
	 * Sets the ebatch of this enroll course.
	 *
	 * @param ebatch the ebatch of this enroll course
	 */
	public void setEbatch(String ebatch);

	/**
	 * Returns the estatus of this enroll course.
	 *
	 * @return the estatus of this enroll course
	 */
	@AutoEscape
	public String getEstatus();

	/**
	 * Sets the estatus of this enroll course.
	 *
	 * @param estatus the estatus of this enroll course
	 */
	public void setEstatus(String estatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EnrollCourse enrollCourse);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EnrollCourse> toCacheModel();

	@Override
	public EnrollCourse toEscapedModel();

	@Override
	public EnrollCourse toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}